; Tauri NSIS Installer Hooks
; This file will be inserted into the NSIS script generated by Tauri
; No need to write a complete script, just define macros

!macro NSIS_HOOK_POSTINSTALL
    ; ========================================
    ; Copy golden database for first-time users
    ; ========================================
    DetailPrint "Setting up initial database..."
    
    ; Create app data directory if not exists
    CreateDirectory "$APPDATA\com.aidaptiv.meetily"
    
    ; Check if database already exists (don't overwrite existing user data)
    IfFileExists "$APPDATA\com.aidaptiv.meetily\meeting_minutes.sqlite" SkipDbCopy 0
    
    ; Copy golden database from installation directory to app data
    ; $INSTDIR is the installation directory (e.g., C:\Program Files\meetily)
    IfFileExists "$INSTDIR\resources\meeting_minutes.sqlite" 0 NoGoldenDb
        DetailPrint "Copying sample database to $APPDATA\com.aidaptiv.meetily\"
        CopyFiles /SILENT "$INSTDIR\resources\meeting_minutes.sqlite" "$APPDATA\com.aidaptiv.meetily\meeting_minutes.sqlite"
        IfErrors CopyFailed CopySuccess
    
    CopyFailed:
        DetailPrint "Warning: Failed to copy sample database"
        Goto SkipDbCopy
    
    CopySuccess:
        DetailPrint "Sample database installed successfully"
        Goto SkipDbCopy
    
    NoGoldenDb:
        DetailPrint "No sample database found in resources"
    
    SkipDbCopy:
        DetailPrint "Database setup completed"


    DetailPrint "========================================"
    DetailPrint "Deploying Local Vulkan Runtime..."
    DetailPrint "========================================"

    ; Strategy: Prefer system's high version; use bundled local DLL if system version is too old or missing
    
    ; 1. Check system version
    StrCpy $R0 0
    IfFileExists "$SYSDIR\vulkan-1.dll" 0 +2
    GetDllVersion "$SYSDIR\vulkan-1.dll" $R0 $R1
    
    DetailPrint "SYSDIR = $SYSDIR"
    IntOp $R2 $R0 / 65536      ; Major
    IntOp $R3 $R0 & 0xFFFF     ; Minor
    DetailPrint "Version = $R2.$R3"

    ; Compare: whether >= 1.2 (65538)
    IntCmp $R0 65538 SystemVersionOK SystemVersionTooOld SystemVersionOK

    SystemVersionOK:
        DetailPrint "System Vulkan is sufficient ($R2.$R3 >= 1.2). Cleaning up local DLL just in case."
        ; If system version is sufficient, delete DLL in App directory to force using system version (prefer driver optimized)
        Delete "$INSTDIR\vulkan-1.dll"
        Goto VulkanDone

    SystemVersionTooOld:
        DetailPrint "System Vulkan missing or too old ($R2.$R3 < 1.2)."
        DetailPrint "Deploying App-Local vulkan-1.dll..."
        
        ; vulkan-1.dll is now bundled directly to $INSTDIR (no copy needed)
        ; Just verify it exists
        IfFileExists "$INSTDIR\vulkan-1.dll" LocalDllReady LocalDllMissing
        
    LocalDllReady:
        DetailPrint "Local Vulkan runtime is ready at $INSTDIR\vulkan-1.dll"
        Goto VulkanDone

    LocalDllMissing:
        DetailPrint "WARNING: Local vulkan-1.dll not found!"

    VulkanDone:
        DetailPrint "Vulkan setup completed."
!macroend

!macro NSIS_HOOK_PREUNINSTALL
    ; Only delete application data in silent mode
    ; In normal mode (with UI), user can choose whether to delete data
    
    ${IfNot} ${Silent}
        ; Non-silent mode: skip automatic deletion, let user decide via UI
        Goto SkipSilentDelete
    ${EndIf}
    
    ; Silent mode: automatically delete application data
    DetailPrint "========================================"
    DetailPrint "Silent mode - Deleting application data..."
    DetailPrint "========================================"
    
    ; Delete application data in %APPDATA%\meetily
    IfFileExists "$APPDATA\meetily" 0 CheckLocalAppData
        DetailPrint "Deleting: $APPDATA\meetily"
        RMDir /r "$APPDATA\meetily"
    
    CheckLocalAppData:
    ; Delete application data in %LOCALAPPDATA%\meetily
    IfFileExists "$LOCALAPPDATA\meetily" 0 CheckAppDataId
        DetailPrint "Deleting: $LOCALAPPDATA\meetily"
        RMDir /r "$LOCALAPPDATA\meetily"
    
    CheckAppDataId:
    ; Delete app data by identifier (com.aidaptiv.meetily)
    IfFileExists "$APPDATA\com.aidaptiv.meetily" 0 CheckLocalAppDataId
        DetailPrint "Deleting: $APPDATA\com.aidaptiv.meetily"
        RMDir /r "$APPDATA\com.aidaptiv.meetily"
    
    CheckLocalAppDataId:
    IfFileExists "$LOCALAPPDATA\com.aidaptiv.meetily" 0 SilentDeleteDone
        DetailPrint "Deleting: $LOCALAPPDATA\com.aidaptiv.meetily"
        RMDir /r "$LOCALAPPDATA\com.aidaptiv.meetily"
    
    SilentDeleteDone:
        DetailPrint "Application data cleanup completed"
    
    SkipSilentDelete:
!macroend
